OFFICE_CENTER = [
":::::::::::::::::::::::::::::::::::::::::.:+***#%@@%#***=..:::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::=#%@@%#=::::::::::::::::::::::::::::::::::::::::::::::",
":::::::::::::::::::::::::::::::::::::::::::::::=+**+=:::::::::::::::::::::::::::::::::::::::::::::::",
"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::",
"#=+*+*++****************************************+*+++++**********************************+***+*+*==#",
"#+*##########:=-====----------------=====--*####*#*#########################=%%#=-%%%%%=*########++#",
"#+*##########:@@%@@@@%%@@@@@@@@@@%%@@@@@@@**######*#########################+*+#*#%#%@@+*########*+#",
"#+*##########:@@%%%%%%%@@@@@@@@@@@@@%%%%@@**######*#########*-+++++++=*#####+@=%@@%####+*########*+#",
"#+*##########:+#%@@%+=+%@@@@@@@@@@@@@@@@%%**######*#########*=**%%%@@**#####+@%@@@@@@+%+*########*+#",
"#+*##########:=+%@%+=+#@@@@%.-%@@@@@@@%%@%**######*#########*=%%%%%+%+-===-*+###%%%%###+*########*+#",
"#+*##########:=======*%@*--:::--=%@@@%%###**######*#########*+@#*%@+==++%%=*+*+*#####**+*########*+#",
"#+*##########:==----=#@@#-:.::::=%@@%*#*##+*######*#####****==*=*%%*#+=++%=#++++=------=+*#######*+#",
"#+*##########:==-::-=#@@*:::.:::-#@@#+#**#+*######*####*+%#%%%%%:-=:--++*#=#####=*%%%%%%%=#######*+#",
"#+*##########:===+*+*@@@%=:=+=-:+@@@%#**##+*######*#####++*+%@@@-##-======-#####=#@@@@%*#=#######*+#",
"#+*##########:=====#@@@@@@+:::-%@@@@@@%###+*###########**@+@%##@-##########=*###=*@@@%+=+-#######*+#",
"#+*##########:==-=-*%@@@@#-::::=@@@@@@@@@@**###########*=+-+#+*%-##*+++=+++-=+##=-+=#%+=*=#######*+#",
"#+*##########:=====+%@@@%*------*@@@@%@@@%**###########+.:::.-=*:##-%@@@=++*+*=+=*=*#%*++=#######*+#",
"#+*##########:=====+%@@@%+------*@@@@%%%%%**##*######=**--=-=+++###-%=++==#**+-*#################*+#",
"#++##########:======#@@@%+------+%%%%#####**########-:.+=-:-=+:.:*#-:#+*:=***+=##################*+#",
"#++##########:======#@@@*-------=+.::::..%**######**:=.-:-=--:::=--..::..:::::::.+###############*+#",
"#++##########:======----:.....--=+.:---:.%**######*#*=+++:::+++-**::=::........:.+###############*+#",
"#++######*#########+::-------.+##+.-+--:.#########*####:====-=+##+.::::..------:.+##*##########*#*+#",
":..::::::::::::::::..:-------..:..=#%....:..:::...:::::::---:::::..----..------:..:::::::::::::::..:",
"@=   *@@*  :%@%= .:=.:-------...==+**.-:.=.:---:...:+++..-=-=-...-+@@%+:.------:... =%@#:  #@@+.  +@",
"::*%%=::=%%#-::-:--:.::-.::.-.:*@@%==::::-::.::..:------:::::-----+%%%#-.:::.-...:-:-::-#%%=::+%%*::",
"@=...*@@*..-%%........................................................................@%:..#@@+...+@",
"=:...-==-..:==:----------------------------------------------------------------------:==:..-==-...:=",
"=--===========.:::::::::::::::::::::::::::::::::::::::::::::::::::::-::-:::::::::-:::.===========--=",
"#+*###########:-:=-:::::::::::::::::::::::=:::::::::::::::::::::::::#-=**::=#=-+:#-:-:#########*#++#",
"#+*###########:-:=-::::::::::::::::::::::.=:::::::::::::::::::::::::-*+=:**-:*-:==::-:###########++#",
]

PAUSE = [
"                                                                                                    ",
"####################################################################################################",
"PA # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE #",
"PAU # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE ",
"PAUS # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE",
"PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUS",
" PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAU",
"# PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PA",
" # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # P",
"E # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # ",
"SE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE #",
"USE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE ",
"AUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE",
"PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUS",
" PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAU",
"# PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PA",
" # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # P",
"E # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # ",
"SE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE #",
"USE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE ",
"AUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE",
"PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUS",
" PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAU",
"# PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PA",
" # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # P",
"E # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # ",
"SE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE #",
"USE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE # PAUSE ",
"####################################################################################################",
"                                                                                                    "
]
